sonar.organization=govuk-once
sonar.projectKey=govuk-once_flex-platform

sonar.sources=gateways, packages

sonar.tests=gateways, packages
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts,**/__mocks__/**,**/__tests__/**

sonar.qualitygate.wait=true
sonar.typescript.tsconfigPaths=gateways/**/tsconfig.json,packages/*/tsconfig.json
sonar.exclusions=**/dist/**,**/coverage/**,**/.turbo/**,**/node_modules/**,**/.gen/**

# Generated code is produced on each build and not committed.
sonar.coverage.exclusions=**/.gen/**,\
  **/*.config.ts

sonar.javascript.lcov.reportPaths=gateways/**/coverage/lcov.info,packages/*/coverage/lcov.info

sonar.javascript.node.maxspace=8192
