import { rm } from "node:fs/promises";
import path from "node:path";

import { checkGateway } from "./check-gateway.ts";
import { checkVersions } from "./compare-schemas.ts";
import { emitContract } from "./emit-contract.ts";
import { bundleEntry, emitEntry } from "./emit-entry.ts";
import { compileValidators, writeValidators } from "./emit-validators.ts";
import {
  CLIENT_DIR,
  GENERATED_DIR,
  RUNTIME_DIR,
  VALIDATORS_DIR,
} from "./layout.ts";
import { loadConfig } from "./load-config.ts";
import { loadVersions, SchemaStoreError } from "./schema-store.ts";

// One generated directory per gateway, holding the two things a gateway produces: what it runs
// and what a caller imports. A gateway is named by its directory rather than by a configuration
// object: the entry point imports `gateway.config.ts` by path and esbuild reads that file when it
// bundles, so the configuration checked here has to be the one read from it in this run, and
// nothing else can be handed in. One run at a time per directory; nothing coordinates two, and a
// gateway is generated by one command. One run per gateway per process, too: Node cannot evict a
// module it has evaluated, so a second run reads the configuration again, and the schemas, which
// are parsed rather than imported, but is served whatever the configuration imports as the first
// run left it.
export async function generate(gatewayDir: string): Promise<void> {
  const dir = path.resolve(gatewayDir);
  const config = await loadConfig(dir);
  const versions = await loadVersions(dir);
  const latest = versions.at(-1);
  // loadVersions already refuses a gateway with no versions. Refused again here rather than
  // defaulted, since a default would generate a gateway with no operations.
  if (latest === undefined) {
    throw new SchemaStoreError(dir, ["holds no versions"]);
  }
  const { schemas } = latest;

  // The schemas are generated from before they are read against anything else, so a schema that
  // is not a valid schema is reported as itself rather than as the disagreement it causes. Then
  // against the versions before them, and only then against the configuration: a contract that
  // breaks its callers is refused whatever the configuration makes of it.
  const compiled = compileValidators(schemas);
  checkVersions(config.id, versions);
  checkGateway(config, schemas);

  // Everything that can refuse the gateway has run, so what is left is writing and bundling. The
  // output is deleted and written again: a run that fails from here fails the command and leaves
  // an incomplete directory, which the next run replaces.
  const outDir = path.join(dir, GENERATED_DIR);
  await rm(outDir, { recursive: true, force: true });
  const runtimeDir = path.join(outDir, RUNTIME_DIR);
  await writeValidators(compiled, path.join(runtimeDir, VALIDATORS_DIR));
  await emitEntry(config.id, runtimeDir);
  await bundleEntry(runtimeDir);
  await emitContract(config.id, schemas, path.join(outDir, CLIENT_DIR), {
    descriptions: Object.fromEntries(
      Object.entries(config.operations).map(([name, operation]) => [
        name,
        operation.description,
      ]),
    ),
  });
}
